package jp.practice.spring.mybatis.dto;

import java.util.Date;

public class Memo extends MemoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column develop.memo.memo
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column develop.memo.update_user
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column develop.memo.update_date
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	private Date updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column develop.memo.memo
	 * @return  the value of develop.memo.memo
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column develop.memo.memo
	 * @param memo  the value for develop.memo.memo
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column develop.memo.update_user
	 * @return  the value of develop.memo.update_user
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column develop.memo.update_user
	 * @param updateUser  the value for develop.memo.update_user
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column develop.memo.update_date
	 * @return  the value of develop.memo.update_date
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column develop.memo.update_date
	 * @param updateDate  the value for develop.memo.update_date
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}