package jp.practice.spring.mybatis.mapper;

import java.util.List;
import jp.practice.spring.mybatis.dto.Login;
import jp.practice.spring.mybatis.dto.LoginExample;
import org.apache.ibatis.annotations.Param;

public interface LoginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	long countByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	int deleteByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	int insert(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	int insertSelective(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	List<Login> selectByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	Login selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	int updateByExampleSelective(@Param("record") Login record, @Param("example") LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	int updateByExample(@Param("record") Login record, @Param("example") LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	int updateByPrimaryKeySelective(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table develop.login
	 * @mbg.generated  Fri May 01 19:12:19 JST 2020
	 */
	int updateByPrimaryKey(Login record);
}